### ISSUE TITLE
Problem with Milk

### ISSUE THREAD

**Issue by TheChampTF** [MattsLab/FlashlightPlus#7]
Hey

So today we had the issue of not being allowed to drink milk from a bucket when flashlight was on.

Guess it might be as the milk removes all the potion effects?

**Comment by MattsLab** [comment]
It all seems to be working on my end, what version of Java are you running on your server?

**Comment by TheChampTF** [comment]
Latest java

**Comment by MattsLab** [comment]
It must have been fixed when I just updated it to 1.10.2, I'll push out an update once I sort out one issue.

**Comment by TheChampTF** [comment]
Okay, sounds great!

**Comment by MattsLab** [comment]
Should be fixed. Check out the latest release.
https://github.com/MattsLab/FlashlightPlus/releases/tag/v1.10-1.0.16
