### ISSUE TITLE
PlayerInteractEvent problem

### ISSUE THREAD

**Issue by TheChampTF** [MattsLab/FlashlightPlus#8]
Hey

Sadly today on latest release I noticed this [here](http://paste.yu8.me/?5e3af403927273bf#lxWI6N6HUfwaNwfqEcMTdsCcgJgVnLg/FXPCXNFm1sU=)

**Comment by MattsLab** [comment]
Check out the newest release. It looks like it was a rookie mistake made by me when I was changing things around to fix issues it was having with the offhand. Added back the check to make sure the item had a name.

Sorry for the inconvenience.
https://github.com/MattsLab/FlashlightPlus/releases/tag/v1.10.2-1.0.17
